version: '3'

services:
  webserver:
    image: php:apache
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - mysql